Extract get_router and add simple test.
jakobhellermann/wasm-server-runner pull request #29
Opened 2022-11-23 01:30 UTC by heisencoder

This PR extracts the logic from `run_server` that creates a new Router into a helper function named `get_router` to make it easier to test without needing to start the full server.

This also adds a simple test that verifies current behavior for returning a br compressed wasm.wasm file.

This change is in preparation for adding support dynamically change the available compression.

See issue #28 for context.

2022-11-23 01:32 UTC, heisencoder commented
Hi @jakobhellermann and @daxpedda -- I'm starting with this simple refactoring PR with a simple test, but plan to later add on support for serving gzip compressed files based on the `accepting-encoding` header.  Please let me know if this overall approach looks like a good start with regard to refactoring and testing.  Thanks! :)

2022-11-23 03:23 UTC, heisencoder commented on src/server.rs
> +}
This code is unchanged as compared to lines 82-107 of the original file.

2022-11-23 13:36 UTC, daxpedda requested changes
Just to clarify, I'm not a maintainer of this repository, so no merge rights, but happy to be pinged to review anyway, thanks!

You should probably not ping [jakobhellermann](https://github.com/jakobhellermann), owners of a repo get notified anyway.

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +        println!(" request headers: {:?}", headers);
I'm assuming this is a debugging leftover?

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +    /// In this request, br is missing from the "accept-encoding" header
This is confusing, the test below does also have `br` in it's `accept-encoding` header, as far as I can see.

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +
This is probably not useful as a comment.

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +        let wasm_file =
Not exactly ideal. I think generally the issue is that `wasm-server-runner` has no CI, so I'm not entirely sure if adding tests that are not really straightforward to run makes sense.

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +        println!("{:?}", &router);
Again I'm assuming debugging leftover.

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +        assert_ne!(result[0..3], Bytes::from(vec![0x1f, 0x8b, 0x08]));
You could probably just load the file that you have the path to already and just compare the whole thing.

2022-11-23 13:36 UTC, daxpedda commented on src/server.rs
> +        //tokio_test::block_on(server).unwrap();
This is probably not useful to leave here.

2022-11-24 01:01 UTC, heisencoder reviewed
Thank you @daxpedda for your comments!  I've uploaded changes based on these comments as a new commit for easier tracking, although I'm happy to do a squash rebase if that's easier for this repo (in any case, I'm assuming that this would get squash merged).

2022-11-24 11:26 UTC, daxpedda requested changes
Otherwise LGTM.

2022-11-24 11:26 UTC, daxpedda commented on src/server.rs
> +    }
I think for this test to be useful, we should probably make a fake WASM file and then compress that. At the moment we are providing a fake already compressed WASM file, so we aren't properly testing the code.

2022-11-24 17:38 UTC, heisencoder commented on src/server.rs
> +    }
I gave this some thought and decided that for this particular case, a more targeted unit test was more appropriate, particularly since the primary goal is to make sure the router is able to choose the correct file.  With regard to testing the compression, I was thinking that that could be addressed by another unit test in wasm_bindgen (although logically the compression could probably be extracted into a separate module).

Heavier-weight testing, I think, would be better placed into a separate PR, ideally with corresponding test automation.

2022-11-24 18:11 UTC, heisencoder commented
I'm closing and moving this review over to #30 , since this change is the first commit in #30

Thanks @daxpedda for your thoughtful comments!

2022-11-24 18:11 UTC, closed without merging